- name: Upload APK artifacts
  uses: actions/upload-artifact@v4
  with:
    name: android-apk-app-${{ inputs.build_type }}
    path: |
      app/build/outputs/apk/app/${{ inputs.build_type }}/*.apk
      app/build/outputs/bundle/app${{ inputs.build_type }}/*.aab
    retention-days: 7
    if-no-files-found: error